ekuriblog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('ckeditor', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
app_name = 'main'
urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('post/<str:slug>', PostView.as_view(), name = 'post'),
    path('category/<str:slug>', CategoryDetailView.as_view(), name='category'),
    path('contact-us', ContactView.as_view(), name='contact'),

    path('admins/create/', AdminPostCreateView.as_view(), name='create_post'),
    path('admins/<int:pk>/delete/',
         AdminPostDeleteView.as_view(), name='delete_post'),
    path('adminedit/<int:pk>/', AdminPostUpdateView.as_view(), name='edit_post'),
    path('search/', SearchView.as_view(), name = 'search'),
    path('admins/post/', AdminPostListView.as_view(), name='list_post'),
    path('post/<str:slug>/', PostView.as_view(), name='post'),
    path('category/<str:slug>/', CategoryDetailView.as_view(), name='category'),

    path('admins/create', AdminPostCreateView.as_view(), name='create_post'),
    path('admins/<int:pk>/delete',
         AdminPostDeleteView.as_view(), name='delete_post'),
    path('adminedit/<int:pk>', AdminPostUpdateView.as_view(), name='edit_post'),
    path('search', SearchView.as_view(), name='search'),
    path('admins/post/', AdminPostListView.as_view(), name='list_post'),

]

main/models.py
from django.db import models
import sys
from django.contrib.auth.models import User
from django.utils import timezone
from autoslug import AutoSlugField
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from PIL import Image
from io import BytesIO
from django.core.files import File
# Create your models here.


class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField()
    date_created = models.DateTimeField(auto_now_add=True)


class Contact(models.Model):
	first_name = models.CharField(max_length=256)
	email = models.EmailField(max_length=256, null=True, blank=True)
	message = models.TextField(null=True, blank=True)
	date_created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.first_name


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = AutoSlugField(populate_from='name')
    image = models.ImageField(upload_to='cat_img', blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name



class Post(models.Model):

    sta = (
        ('published', 'published'),
        ('draft', 'draft'),
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=500)
    slug = AutoSlugField(populate_from='title')
    image_1 = models.ImageField(null=True)
    excerpt = models.TextField(null=True, blank=True)

    content = RichTextUploadingField()
    date_created = models.DateTimeField(auto_now_add=True)
    view_count = models.PositiveIntegerField(default=0)
    status = models.CharField(max_length=30, choices=sta, default='published')
    # objects  = PostManager()

    class Meta:
        ordering = ('-date_created',)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        new_image = self.reduce_image_size(self.image_1)
        self.image_1 = new_image
        super().save(*args, **kwargs)

    def reduce_image_size(self, profile_pic):
        print(profile_pic)
        img = Image.open(profile_pic)
        thumb_io = BytesIO()
        img.save(thumb_io, 'jpeg', quality=50)
        new_image = File(thumb_io, name=profile_pic.name)
        return new_image

class Comment(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField(null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date_created']

    def __str__(self):
        return self.post.title

class ContactUs(models.Model):
    facebook = models.CharField(max_length=500)
    instagram = models.CharField(max_length=500)
    twitter = models.CharField(max_length=500)
    whatsapp = models.CharField(max_length=500)
    phone_number = models.CharField(max_length=500)
    email = models.EmailField()
    address = models.CharField(max_length=500)


class NewsLetter(models.Model):
    email = models.EmailField(null=True, blank=True)

main/forms.py
from django import forms
from .models import Comment, Post, Contact
from django_quill.forms import QuillFormField
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'content']

        widgets = {
            "name": forms.TextInput(attrs={
                'name': 'name',
                'class': 'form-control',
            				'id': 'firstName',
            				'required': True
            }),
            "email": forms.EmailInput(attrs={
                'name': 'email',
                'class': 'form-control',
            				'id': 'email',
            				'required': True
            }),
            "content": forms.Textarea(attrs={
                'name': 'content',
                'class': 'form-control',
            				'id': 'content',
            				'rows': 5,
            				'columns': 5,
            				'required': True
            }),

        }


class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = "__all__"



class AuthenticationForm(forms.Form):
	username = forms.CharField(widget=forms.TextInput())
	password = forms.CharField(widget=forms.PasswordInput())


class ContactForm(forms.ModelForm):
	class Meta:
		model = Contact
		fields = "__all__"

		widgets = {
			"first_name": forms.TextInput(attrs={
				'name': 'firstName',
				'class': 'form-control',
				'id': 'firstName',
				'required': True
			}),
			"email": forms.EmailInput(attrs={
				'name': 'email',
				'class': 'form-control',
				'id': 'email',
				'required': True
			}),
			"message": forms.Textarea(attrs={
				'name': 'message',
				'class': 'form-control',
				'id': 'message',
				'rows': 5,
				'columns': 5,
				'required': True
			}),

		}

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Admin
from django.views.generic import TemplateView, DetailView, CreateView, DeleteView, UpdateView, ListView, FormView, View
from .models import Post, Category, Comment
from .forms import AuthenticationForm, CommentForm, PostForm, ContactForm
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
# Create your views here


class HomeView(TemplateView):
    template_name = 'index.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        first = Post.objects.last()
        all = Post.objects.filter(
            status='published').order_by('date_created')[:10]
        post = Post.objects.filter(
            status='published').order_by('view_count')[:10]
        latest_cele = Post.objects.filter(Q(category = 5) & Q(
            status='published')).order_by('-date_created')
        latest_enter = Post.objects.filter(Q(category=1) & Q(
            status='published')).order_by('-date_created')
        last = Post.objects.first()
        context['first'] = first
        context['all'] =all
        context['last'] = last
        context["post"] = post 
        context['cele'] = latest_cele
        context['enter'] = latest_enter
        context['cele_1'] = first
        context['enter_1'] = last

        return context


class PostView(TemplateView):
    template_name = 'single-post.html'
    # context_object_name = 'post'
    # model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug = kwargs['slug']
        post = Post.objects.get(slug=slug)
        post.view_count += 1
        post.save()
        context['post'] = post
        return context

    def post(self, request, *args, **kwargs):
        new_comment = Comment(content=request.POST.get('content'),
                              name=request.POST.get('name'),
                              email=request.POST.get('email'),
                              post=self.get_object())
        new_comment.save()
        return self.get(self, request, *args, **kwargs)


class SearchView(TemplateView):
    template_name = 'search-result.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        kw = self.request.GET['keyword']
        result = Post.objects.filter(Q(title__icontains=kw) | Q(
            content__icontains=kw) | Q(excerpt__icontains=kw))
        context["result"] = result
        return context


class CategoryDetailView(TemplateView):
    template_name = 'category.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        url_slug = kwargs['slug']
        allcategory = Category.objects.all()
        category = Category.objects.get(slug=url_slug)
        post = Post.objects.filter(Q(category=category) & Q(status = 'published'))
        top = Post.objects.filter(Q(category=category) & Q(status='published')).order_by('view_count')[:4]
        context['post'] = post
        context['cat'] = category
        context['top'] = top
        return context

class SearchView(TemplateView):
	template_name = 'search-result.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		kw = self.request.GET['keyword']
		results = Post.objects.filter(Q(title__icontains=kw) | Q(content__icontains=kw) | Q(excerpt__icontains=kw))
		context['results'] = results 
		return context

class ContactView(TemplateView):
    template_name = 'contact.html'

class AdminPostCreateView(CreateView):
    template_name = 'admin/create.html'
    model = Post
    fields = ['category',
              'title', 'image_1', 'excerpt', 'content', 'status']
    success_url = reverse_lazy('main:list_post')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            pass
        else:
            return redirect('/accounts/login/?next=/admins/create/')

        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        author = self.request.user
        content = self.request.GET('editor_content')
        return super().get_queryset()

    def form_valid(self, form):
        form.instance.author = self.request.user
        messages.success(self.request, "Successful")
        form.save()
        return super().form_valid(form)


class AdminPostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('main:list_post')


class AdminPostListView(ListView):
    model = Post
    context_object_name = 'post_list'
    template_name = 'admin/postlist.html'


class AdminPostUpdateView(UpdateView):
    template_name = 'admin/create.html'
    model = Post
    success_url = reverse_lazy('main:list_post')
    fields = ['category',
              'title', 'image_1', 'excerpt', 'content', 'status']

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            pass
        else:
            return redirect('/accounts/login/?next=/admins/post/')

        return super().dispatch(request, *args, **kwargs)

class AdminLogoutView(View):
	
	def get(self, request):
		logout(request)
		return redirect('ecommerceapp:adminhome')

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Ekuri's Blog</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Ekuri's Blog" name="keywords">
    <meta content="Ekuri's Blog" name="description">
    {% block ogmeta %}{% endblock ogmeta %}
    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet">   
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" integrity="sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/style.css' %} " rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'src/jquery.floating-social-share.css' %} " />
    <script src="https://cdn.fastcomments.com/js/embed-v2.min.js"></script>
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4627919728280348"
     crossorigin="anonymous"></script>
</head>
{% block style %}{% endblock style %}
<body>
    <!-- Topbar Start -->
    <div class="container-fluid">
        <div class="row align-items-center bg-light px-lg-5">
            <div class="col-12 col-md-8">
                <div class="d-flex justify-content-between">
                    <div class="bg-primary text-white text-center py-2" style="width: 100px;">Trending</div>
                    <div class="owl-carousel owl-carousel-1 tranding-carousel position-relative d-inline-flex align-items-center ml-3" style="width: calc(100% - 100px); padding-left: 90px;">
                        
                        {% for po in trend %}
                          <div class="text-truncate"><a class="text-secondary" href="{% url 'main:post' po.slug %}">
                            {{po.title}}
                          </a></div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-md-4 text-right d-none d-md-block">
                Monday, January 01, 2045
            </div>
        </div>
        <div class="row align-items-center py-2 px-lg-5">
            <div class="col-lg-4">
                <a href="{% url 'main:index' %}" class="navbar-brand d-none d-lg-block">
                    <h1 class="m-0 display-5 text-uppercase"><span class="text-primary">Ekuri's </span>Blog</h1>
                </a>
            </div>
            
        </div>
    </div>
    <!-- Topbar End -->


    <!-- Navbar Start -->
    <div class="container-fluid p-0 mb-3">
        <nav class="navbar navbar-expand-lg bg-light navbar-light py-2 py-lg-0 px-lg-5">
            <a href="{% url 'main:index' %}" class="navbar-brand d-block d-lg-none">
                <h1 class="m-0 display-5 text-uppercase"><span class="text-primary">Ekuri's </span>Blog</h1>
                </a>
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between px-0 px-lg-3" id="navbarCollapse">
                <div class="navbar-nav mr-auto py-0">
                    <a href="{% url 'main:index' %}" class="nav-item nav-link active">Home</a>
                    
                    {% for cat in all_categories %}
                      <a href="{% url 'main:category' cat.slug %}" class="nav-item nav-link">
                        {{cat.name}}
                      </a>
                    {% endfor %}
                      
                    

                    
                  
                    <a href="{% url 'main:contact' %}" class="nav-item nav-link">Contact</a>
                </div>
                <div class="input-group ml-auto" style="width: 100%; max-width: 300px;">
                    <input type="text" class="form-control" placeholder="Keyword">
                    <div class="input-group-append">
                        <button class="input-group-text text-secondary"><i
                                class="fa fa-search"></i></button>
                    </div>
                </div>
            </div>
        </nav>
    </div>
    <!-- Navbar End -->
        {% block content %}
      
    {% endblock content %}    

      
    
    <!-- Footer Start -->
<div class="container-fluid bg-light pt-5 px-sm-3 px-md-5">
    <div class="row">
        <div class="col-lg-3 col-md-6 mb-5">
            <a href="{% url 'main:index' %}" class="navbar-brand">
                <h3 class="mb-2 mt-n2 display-6 text-uppercase"><span class="text-primary">Ekuri's</span> Blog</h3>
            </a>
            <p>
                Ekuri's Blog Brings to you latest Entertainment News and Celebrity Gists.
            </p>
            <p>Follow us on Social media</p>
            <div class="d-flex justify-content-start mt-4">
                <a class="btn btn-outline-secondary text-center mr-2 px-0" style="width: 38px; height: 38px;"
                    href="{{contactus.twitter}}"><i class="fab fa-twitter"></i></a>
                <a class="btn btn-outline-secondary text-center mr-2 px-0" style="width: 38px; height: 38px;"
                    href="{{contactus.facebook}}"><i class="fab fa-facebook-f"></i></a>
                <a class="btn btn-outline-secondary text-center mr-2 px-0" style="width: 38px; height: 38px;"
                    href="{{contactus.twitter}}"><i class="fab fa-linkedin-in"></i></a>
                <a class="btn btn-outline-secondary text-center mr-2 px-0" style="width: 38px; height: 38px;"
                    href="{{contactus.instagram}}"><i class="fab fa-instagram"></i></a>
                <a class="btn btn-outline-secondary text-center mr-2 px-0" style="width: 38px; height: 38px;"
                    href="{{contactus.address}}"><i class="fab fa-youtube"></i></a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mb-5">
            <h4 class="font-weight-bold mb-4">Categories</h4>
            <div class="d-flex flex-wrap m-n1">
                {% for cat in all_categories %}
                <a href="{% url 'main:category' cat.slug %}" class="btn btn-sm btn-outline-secondary m-1">
                    {{cat.name}}
                </a>
                {% endfor %}
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mb-5">
            <h4 class="font-weight-bold mb-4">Tags</h4>
            <div class="d-flex flex-wrap m-n1">
                {% for cat in all_categories %}
                <a href="{% url 'main:category' cat.slug %}" class="btn btn-sm btn-outline-secondary m-1">
                    {{cat.name}}
                </a>
                {% endfor %}
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mb-5">
            <h4 class="font-weight-bold mb-4">Quick Links</h4>
            <div class="d-flex flex-column justify-content-start">
                <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right text-dark mr-2"></i>About</a>
                <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right text-dark mr-2"></i>Advertise</a>
                <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right text-dark mr-2"></i>Privacy &
                    policy</a>
                <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right text-dark mr-2"></i>Terms &
                    conditions</a>
                <a class="text-secondary" href="{% url 'main:contact' %}"><i class="fa fa-angle-right text-dark mr-2"></i>Contact</a>
            </div>
        </div>
    </div>
</div>
    <div class="container-fluid py-4 px-sm-3 px-md-5">
        <p class="m-0 text-center">
            &copy; <a class="font-weight-bold" href="#">Ekuri's Blog</a>. All Rights Reserved. 
			
			<!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
			Designed by <a class="font-weight-bold" href=""></a>
        </p>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-dark back-to-top"><i class="fa fa-angle-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <!-- <script src="lib/easing/easing.min.js"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js" integrity="sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script type="text/javascript" src="{% static 'src/jquery.floating-social-share.js' %} "></script>
    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %} "></script>

    <script>
        window.FastCommentsUI(document.getElementById('fastcomments-widget'), {
            "tenantId": "7zQ5F42Z70q8"
        });
    </script>
    <script>
        $(".content").floatingSocialShare({
            buttons: [
                "facebook", "pinterest", "telegram", "twitter", "whatsapp"
            ],
            text: { 'default': 'share with: ', 'facebook': 'share with facebook' },
            text_title_case: true,
            popup: false,
            place: "content-left",
            // url: "https://github.com/ozdemirburak/jquery-floating-social-share"
        });
    </script>
</body>

</html>

main/templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="container">
            <nav class="breadcrumb bg-transparent m-0 p-0">
                <a class="breadcrumb-item" href="{% url 'main:index' %}">Home</a>
                <a class="breadcrumb-item" href="#">Category</a>
                <span class="breadcrumb-item active">
                    {{cat.name}}
                </span>
            </nav>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- News With Sidebar Start -->
    <div class="container-fluid py-3">
        <div class="container">
            <div class="row content">
                <div class="col-lg-8">
                    <div class="row">
                        <div class="col-12">
                            <div class="d-flex align-items-center justify-content-between bg-light py-2 px-4 mb-3">
                                <h3 class="m-0">
                                    {{cat.name}}
                                </h3>
                                <a class="text-secondary font-weight-medium text-decoration-none" href="">View All</a>
                            </div>
                        </div>
                        
                        {% for po in top %}
                          <div class="col-lg-6">
                            <div class="position-relative mb-3">
                                <img class="img-fluid w-100" src="{{po.image_1.url}}" style="object-fit: cover;">
                                <div class="overlay position-relative bg-light">
                                    <div class="mb-2" style="font-size: 14px;">
                                        <a href="{% url 'main:category' po.category %}">
                                            {{po.category}}
                                        </a>
                                        <span class="px-1">/</span>
                                        <span>
                                            {{po.date_created|date}}
                                        </span>
                                    </div>
                                    <a class="h4" href="{% url 'main:post' po.slug %}">
                                        {{po.title}}
                                    </a>
                                    <p class="m-0">
                                        {{Po.excerpt|safe|slice:50}}
                                        </p>
                                </div>
                            </div>
                        </div>  
                        {% endfor %}
                        
                    </div>
                    
                    <div class="row">
                        
                        {% for po in post %}
                            <div class="col-lg-6">
                            <div class="d-flex mb-3 h-100">
                                <img src="{{po.image_1.url}}" style="width: 100px; height: 100%; object-fit: cover;">
                                <div class="w-100 d-flex flex-column justify-content-center bg-light px-3" style="height: 100%;">
                                    <div class="mb-1" style="font-size: 13px;">
                                        <a href="{% url 'main:category' cat.slug %}">
                                            {{po.category}}
                                        </a>
                                        <span class="px-1">/</span>
                                        <span>
                                            {{po.date_created|date}}
                                        </span>
                                    </div>
                                    <a class="h6 " href="{% url 'main:post' po.slug %}">
                                        {{po.title}}
                                    </a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                            
                        
                    </div>
                    {% comment %} <div class="row">
                        <div class="col-12">
                            <nav aria-label="Page navigation">
                              <ul class="pagination justify-content-center">
                                <li class="page-item disabled">
                                  <a class="page-link" href="#" aria-label="Previous">
                                    <span class="fa fa-angle-double-left" aria-hidden="true"></span>
                                    <span class="sr-only">Previous</span>
                                  </a>
                                </li>
                                <li class="page-item active"><a class="page-link" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item">
                                  <a class="page-link" href="#" aria-label="Next">
                                    <span class="fa fa-angle-double-right" aria-hidden="true"></span>
                                    <span class="sr-only">Next</span>
                                  </a>
                                </li>
                              </ul>
                            </nav>
                        </div>
                    </div> {% endcomment %}
                </div>

                {% include 'sidebar.html' %}
        </div>
    </div>
    </div>
    <!-- News With Sidebar End -->
{% endblock content %}

main/templates/single-post.html
{% extends 'base.html' %} {% load static %} {% block ogmeta %}
<meta property="og:site_name" content="Ekuri's Blog" />
<meta property="og:title" content="{{post.title}}" />
<meta property="og:description" content="{{post.excerpt|safe}}" />
<meta property="og:url" content="{{post.get_absolute_url}}" />
<meta property="og:type" content="article" />
<meta property="article:publisher" content="https://www.ekurisblog.com" />
<meta property="article:section" content="{{post.category}}" />
<meta property="article:tag" content="{{post.category}}" />
<meta property="og:image" content="{{post.image_1.url}}" />
<meta property="og:image:secure_url" content="{{post.image_1.url}}" />
<meta property="og:image:width" content="1280" />
<meta property="og:image:height" content="640" />
{% endblock ogmeta %} {% block style %}
<style>
  @media only screen and (max-width: 600px) {
    img {
      width: 90vw !important;
      height: 100%;
      object-fit: cover;
    }

    iframe {
      width: 90vw !important;
      object-fit: cover;
    }

    video {
      width: 100vw !important;
    }

    .image_1 {
      width: 100% !important;
      height: 100%;
      object-fit: contain;
    }

  }


  .tit>img {
    width: 100% !important;
    height: 100% !important;
    object-fit: contain;
  }

  video {
    width: 95vw !important;
    height: 100%;
    object-fit: contain;
  }

  iframe {
    width: 90vw !important;
    object-fit: contain;
  }
</style>

{% endblock style %} {% block content %}
<!-- Breadcrumb Start -->
<div class="container-fluid">
  <div class="container">
    <nav class="breadcrumb bg-transparent m-0 p-0">
      <a class="breadcrumb-item" href="{% url 'main:index' %}">Home</a>
      <a class="breadcrumb-item" href="#">Category</a>
      <span class="breadcrumb-item active"> {{post.category.name}} </span>
    </nav>
  </div>
</div>
<!-- Breadcrumb End -->

<!-- News With Sidebar Start -->
<div class="container-fluid py-3">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <div class="row">
          <div class="col-lg-12">
            <div class="mb-3">
              <div class="content">
                <img src="{{post.image_1.url}}" class="image_1" />
              </div>
              <div class="mb-1 content" style="font-size: 13px">
                <a href=""> {{post.category}} </a>
                <span class="px-1">/</span>
                <span> {{post.date_created|date}} </span>
              </div>
              <a class="h6 m-0" href="{% url 'main:post' post.slug %}">
                {{post.title}}
              </a>
              <div class="tit">
                {{post.excerpt|safe}}
                <p class="text-wrap">
                  {{post.content|safe}}
                </p>
                <div id="fastcomments-widget"></div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {% include 'sidebar.html' %}
    </div>
  </div>

</div>
<!-- News With Sidebar End -->
{% endblock content %}